### ISSUE TITLE
The meauthz source passes the applicationId as a query parameter

### ISSUE THREAD

**Issue by rvanlaarhoven** [digipolisantwerp/authz_module_nodejs#18]
The meauthz source passes the applicationId as a query parameter, which is not valid for the v1 of the meauthz api. The applicationId is expected to be passed in the path (e.g. `/applications/:applicationId/permissions`)

See here:

https://github.com/digipolisantwerp/authz_module_nodejs/blob/21683930a7f08bf8c59c2ea78133c647f7420c0f/lib/services/datasources/meauthz.permissions.js#L16

This results in a `400` with the following response body:

```json
{
    "message": "unknown route"
}
```

Simply removing the `qs` parameter from the request solves the problem, but I don't know if this affects the other versions of the api.

**Comment by vademo** [comment]
At this moment v2 of the MeAuthz api is used as default for new applications. Here the `applicationId` is expected as a query param. 

If you would like to use v1, feel free to add this implementation as a separate datasource. This addition would be appreciated. 

However there's also support for external [External sources](https://github.com/digipolisantwerp/authz_module_nodejs#external-authorization-source) which you can use without having to modify this module.

**Comment by rvanlaarhoven** [comment]
Okay, I think it would be nice to define that in the documentation, since we lost quite a lot of time testing the various versions (v4 & v3) and since they both resulted in errors I went back to v1 that worked with manual requests...
